project: 
  type: website

website: 
  page-navigation: true
  title: "MA378" 
  site-url: "https://mkov77.github.io/MA378-Project" 
  repo-url: "https://github.com/mkov77/MA378-Project"
  repo-actions: [source]
  
  page-footer:
    right: "Michaela Kovalsky - Math 378 Final Project"
  
  sidebar:
    background: "#ffb3b3"
    favicon: images/favicon.ico
    pinned: true
    align: center

    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/code.qmd
        text: Penguins EDA
      - href: content/model.qmd
        text: Model

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
